In [5]:
%load_ext autoreload
%autoreload 2

import sys
sys.path.append('../')
from datasets import load_dataset, load_from_disk
from hydra import compose, initialize
from utils.configuration import list_detector_model_names, list_hydra_group_options
with initialize(version_base=None, config_path="../conf"):
    cfg = compose(
        config_name="config",
        overrides=["detector=bert"]
    )
    
detectors = list_detector_model_names("../conf", "detector")
print(detectors)

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload
['BERT-Defense', 'binoculars-falcon-7b', 'FastDetectGPT', 'radar', 'RoBERTa-Defense']

## Baseline detection performance

In [6]:
from pathlib import Path

from utils.evaluation.Metrics import Metrics
from utils.evaluation.ResultsReportBuilder import build_detector_table

results_dir = Path(".." / Path(cfg.experiment.paths.results_dir) )
build_detector_table(results_dir, 
                                      detectors, 
                                      baseline_regime="free_llm",
                                      n_bootstrap=1000, 
                                      random_seed=42)

                            AUROC FREE-LLM             TPR@1%FPR
                             mean ± 95% CI         mean ± 95% CI
Detector
BERT-Defense          0.210 [0.203, 0.217]  0.001 [0.000, 0.003]
binoculars-falcon-7b  0.983 [0.980, 0.985]  0.935 [0.924, 0.942]
FastDetectGPT         0.990 [0.989, 0.992]  0.912 [0.891, 0.929]
radar                 0.913 [0.909, 0.918]  0.668 [0.635, 0.692]
RoBERTa-Defense       0.569 [0.560, 0.578]  0.019 [0.011, 0.029]

## 2 Robustness under H2L rewriting

In [4]:

from utils.evaluation.ResultsReportBuilder import build_h2l_robustness_table


detector_table = build_h2l_robustness_table(results_dir, detectors, n_bootstrap=100, random_seed=42)

In [4]:
detector_table

,AUROC H2L,ΔAUROC H2L,TPR@1%FPR H2L,ΔTPR@1%FPR H2L
,mean [95% CI],mean [95% CI],mean [95% CI],mean [95% CI]
Detector,,,,
BERT-Defense,"0.472 [0.452, 0.491]","0.225 [0.203, 0.243]","0.011 [0.004, 0.019]","0.009 [0.002, 0.017]"
binoculars-falcon-7b,"0.727 [0.713, 0.742]","-0.269 [-0.283, -0.254]","0.127 [0.086, 0.162]","-0.846 [-0.881, -0.810]"
FastDetectGPT,"0.901 [0.891, 0.909]","-0.097 [-0.107, -0.089]","0.382 [0.323, 0.435]","-0.591 [-0.650, -0.540]"
radar,"0.639 [0.617, 0.660]","-0.351 [-0.372, -0.332]","0.099 [0.065, 0.125]","-0.703 [-0.757, -0.606]"
RoBERTa-Defense,"0.677 [0.654, 0.697]","0.037 [0.017, 0.058]","0.026 [0.004, 0.063]","-0.000 [-0.023, 0.019]"

## 4.3 Robustness under LLM2L rewriting

In [1]:


from utils.evaluation.ResultsReportBuilder import build_llm2l_robustness_table


build_llm2l_robustness_table(results_dir, detectors, n_bootstrap=100, random_seed=42)

# from utils.evaluation.BootstrapMetrics import bootstrap_metrics


# bootstrap_metrics = bootstrap_metrics(metrics, cfg.experiment.evaluation.bootstrap.n)

ModuleNotFoundError: No module named 'utils'